// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechCommerce.Data.Contexts;

#nullable disable

namespace TechCommerce.Migrations
{
    [DbContext(typeof(TechContext))]
    [Migration("20250226130104_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechCommerce.Data.Models.ProductAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.AttributeValue", b =>
                {
                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CategoryRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AttributeId", "Value");

                    b.HasIndex("CategoryRef");

                    b.ToTable("AttributeValues");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.Category", b =>
                {
                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryNameRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryName");

                    b.HasIndex("CategoryNameRef");

                    b.HasIndex("ProductId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.CategoryAttribute", b =>
                {
                    b.Property<string>("CategoryRef")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("AttributesRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryRef", "AttributesRef");

                    b.HasIndex("AttributesRef");

                    b.ToTable("CategoryAttributes");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.ProductCategory", b =>
                {
                    b.Property<string>("CategoryRef")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ProductRef")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryRef", "ProductRef");

                    b.HasIndex("ProductRef");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.Warehouse", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.AttributeValue", b =>
                {
                    b.HasOne("TechCommerce.Data.Models.ProductAttribute", "ProductAttribute")
                        .WithMany("AttributeValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechCommerce.Data.Models.Category", "Category")
                        .WithMany("AttributeValues")
                        .HasForeignKey("CategoryRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductAttribute");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.Category", b =>
                {
                    b.HasOne("TechCommerce.Data.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryNameRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechCommerce.Data.Models.Product", null)
                        .WithMany("Categories")
                        .HasForeignKey("ProductId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.CategoryAttribute", b =>
                {
                    b.HasOne("TechCommerce.Data.Models.ProductAttribute", "ProductAttribute")
                        .WithMany("CategoryAttributes")
                        .HasForeignKey("AttributesRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechCommerce.Data.Models.Category", "Category")
                        .WithMany("CategoryAttributes")
                        .HasForeignKey("CategoryRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductAttribute");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.ProductCategory", b =>
                {
                    b.HasOne("TechCommerce.Data.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechCommerce.Data.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.Warehouse", b =>
                {
                    b.HasOne("TechCommerce.Data.Models.Product", "Product")
                        .WithMany("Warehouses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.ProductAttribute", b =>
                {
                    b.Navigation("AttributeValues");

                    b.Navigation("CategoryAttributes");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.Category", b =>
                {
                    b.Navigation("AttributeValues");

                    b.Navigation("CategoryAttributes");

                    b.Navigation("ProductCategories");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("TechCommerce.Data.Models.Product", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("ProductCategories");

                    b.Navigation("Warehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
