apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
stringData:
  ConnectionStrings__Default: "Server=fbas23sql.database.windows.net,1433;Initial Catalog=23sql;User ID=nightcall018;Password=Elvin_123;Encrypt=True;TrustServerCertificate=True"
  JWT__Key: "42704d34-0361-4b61-8776-7fcadf37fbdb"
  JWT__EmailKey: "795b2af6-6017-45dd-aeaf-52f6686fa3db"
  JWT__Issuer: "your-app"
  JWT__Audience: "your-app-users"
  ElasticConfiguration__Uri: "https://my-deployment-5069bb.es.francecentral.azure.elastic-cloud.com"
  ElasticConfiguration__ApiKey: "d1RyUDJwWUJGczlGX1dONVd5eXU6WjhNdVFmUkE4VE9FV2p3akVRMWpfUQ=="
  ElasticConfiguration__DefaultIndex: "users"
  Encryption__SecretKey: "SuperSecretKeyThatShouldBeStoredSecurely"
  Smtp__Host: "smtp.gmail.com"
  Smtp__Port: "587"
  Smtp__User: "profbat018@gmail.com"
  Smtp__Password: "llsrjucbeoragtpi"
  Blob__ConnectionString: "DefaultEndpointsProtocol=https;AccountName=232storage;AccountKey=SGglCF+Ih66V4oEvmjM9wBXsPoX2WFsT3QRuu03z0lscBa4PQqBhJlvMLlIfU2c1ubDLlDfOHYyx+AStjF3UIA==;EndpointSuffix=core.windows.net"
